version: 7.22.0.{build}
branches:
  only:
  - master
  - develop
image: Visual Studio 2022
environment:
  nodejs_version: "20"
install:
- ps: Install-Product node $env:nodejs_version
- ps: |
    Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile dotnet-install.ps1
    ./dotnet-install.ps1 -Channel 7.0
    ./dotnet-install.ps1 -Channel 8.0
    dotnet --info
before_build:
- ps: >-
    if (!(Test-Path -Path ".\.nuget" ))

    {
      New-Item -ItemType "directory" -Path ".\.nuget"
    }
    if (!(Test-Path -Path ".\.nuget\packages" ))

    {
      New-Item -ItemType "directory" -Path ".\.nuget\packages"
    }
- ps: dotnet restore
build_script:
- ps: dotnet pack -c Release --property:PublishDir=artifacts
test_script:
- ps: dotnet test
artifacts:
- path: artifacts\*.nupkg
