name: Build, Test and Publish to Nuget

on:
  workflow_dispatch:

jobs:
  buildAndTestStage:
    runs-on: windows-latest
    steps:

      # Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup .NET 8
      - name: Setup dotnet 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
   
      # Setup Node.js
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20  

      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version

      # Create .nuget directory
      - name: Create .nuget directory
        shell: pwsh
        run: |
          if (!(Test-Path -Path ".\.nuget" ))
          {
            New-Item -ItemType "directory" -Path ".\.nuget"
          }
          if (!(Test-Path -Path ".\.nuget\packages" ))
          {
            New-Item -ItemType "directory" -Path ".\.nuget\packages"
          }
      
      # Dotnet restore + build
      - name: Install dependencies
        run: dotnet restore /nowarn:netsdk1138
      - name: Clean
        run: dotnet clean
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Dotnet test 
      - name: Test with dotnet
        run: dotnet test --no-build --configuration Release --logger trx --results-directory "TestResults"

      # - name: Upload dotnet test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: dotnet-results
      #     path: TestResults
      #   # Use always() to always run this step to publish test results when there are test failures
      #   if: ${{ always() }}

       # Test reporting
      - name: Test Reporter
        uses: dorny/test-reporter@v1.9.1
        if: always()
        with:
          name: DotNET Tests
          path: "TestResults/*.trx"                            
          reporter: dotnet-trx
          fail-on-error: true  

  # publishToNugetStage:
  #   needs: buildAndTestStage
  #   runs-on: windows-latest
  #   steps:
    
    
